services:
  # BDD
  db:
    image: postgres:15-alpine
    container_name: jobingo-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    networks:
      - prod_network

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: jobingo-backend
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
    depends_on:
      - db
    networks:
      - prod_network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jobingo-api.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.jobingo-api.entrypoints=websecure"
      - "traefik.http.routers.jobingo-api.tls.certresolver=myresolver"
      - "traefik.http.routers.jobingo-api.priority=100"
      - "traefik.http.services.jobingo-api.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: jobingo-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - prod_network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jobingo-web.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.jobingo-web.entrypoints=websecure"
      - "traefik.http.routers.jobingo-web.tls.certresolver=myresolver"
      - "traefik.http.routers.jobingo-web.priority=1"
      - "traefik.http.services.jobingo-web.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  prod_network:
    driver: bridge
  proxy:
    external: true

volumes:
  prod_postgres_data:
